name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - feature/updates-build
  # Allows manual trigger
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

# More TBA
